vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%app.path.product_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
