easy_admin:
  site_name: ' <em style ="font-size:80%">Admin WebShop </em>'
  design:
    form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
    number: '%.2f'
  list:
    batch_actions: ['delete']
