easy_admin:
  design:
    menu:
      - label: 'Shop'
        icon: 'newspaper-o'
        children:
          - {entity: 'Product', icon: 'store-alt', label: 'Products'}
          - {entity: 'Category', icon: 'layer-group', label: 'Categories'}
          - {entity: 'User', icon: 'user', label: 'User'}
          - {entity: 'Comment', icon: 'comments', label: 'Comments'}
          - {entity: 'Specificities', icon: 'list', label: 'Specificities'}
          - {entity: 'Image', icon: 'image', label: 'Images'}