easy_admin:
  entities:
    Image:
      class: App\Entity\Image
      list:

        help: 'The items in this entity can be directly deleted here'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','filename','products','createdAt', { property: 'filename', type: 'image', base_path: '%app.path.product_image%' } ]

