easy_admin:
  entities:
    OrderingProduct:
      class: App\Entity\OrderingProduct

      list:
        help: 'The items in this entity can NOT be deleted here, Products must be = 0'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
#      form:
#        fields:
#          - {property: 'title'}
#          - {property: 'catDescription'}
