easy_admin:
  entities:
    Theme:
      class: App\Entity\Theme
      list:
        help: 'The items in this entity can be directly deleted here'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','name','products','createdAt']
      form:
        fields:
          - {property: 'name'}
          - {property: 'createdAt'}
