easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        help: 'The items in this entity can NOT be deleted here, delete it in Comments before'
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        fields: ['id','username','email','password','createdAt','comments','orderings']
      form:
        fields:
          - {property: 'username'}
          - {property: 'email'}
          - {property: 'password'}
          - {property: 'createdAt'}
